/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#0040a1",
        "surface-container-high": "#dee8ff",
        "surface-variant": "#d8e3fb",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-container": "#ccd8ff",
        "inverse-primary": "#b2c5ff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container": "#e7eeff",
        "on-surface-variant": "#424654",
        secondary: "#515f74",
        "on-surface": "#111c2d",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-container": "#d5e3fc",
        "on-background": "#111c2d",
        "primary-container": "#0056d2",
        "outline-variant": "#c3c6d6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffd29e",
        "surface-dim": "#cfdaf2",
        "on-primary-fixed": "#001847",
        "surface-container-low": "#f0f3ff",
        outline: "#737785",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#57657a",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-container-highest": "#d8e3fb",
        "inverse-on-surface": "#ecf1ff",
        "surface-tint": "#0056d2",
        tertiary: "#663f00",
        "on-secondary-fixed": "#0d1c2e",
        "on-tertiary-fixed": "#2a1700",
        background: "#f9f9ff",
        "primary-fixed": "#dae2ff",
        "secondary-fixed": "#d5e3fc",
        "inverse-surface": "#263143",
        "on-secondary-fixed-variant": "#3a485b",
        "tertiary-container": "#865400",
        "tertiary-fixed": "#ffddb8",
        "on-secondary": "#ffffff",
        primary: "#0040a1",
        surface: "#f9f9ff",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#b9c7df",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        ambient: "0 12px 40px rgba(17, 28, 45, 0.06)",
        ambientSoft: "0 12px 40px rgba(17, 28, 45, 0.03)",
      },
    },
  },
  plugins: [],
};
